CREATE TABLE IF NOT EXISTS usuario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    username VARCHAR(100),
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(255) NOT NULL
);

INSERT INTO usuario (nome, username, email, senha)
    VALUES ('Samuel', 'smg', 'samuelssousaky@gmail.com', 'teste');